env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - prettier
rules:
  prettier/prettier:
    - error
    - endOfLine: auto
  react/react-in-jsx-scope: off

overrides:
  - files: ["components/ui/**/*"]
    rules: {}
