# Stage 1: Build the application
FROM node:20 AS builder

WORKDIR /app

COPY package*.json ./
COPY ./prisma ./prisma
COPY ./.env ./.env
RUN npm ci

RUN npx prisma generate

COPY . .

ARG NEXT_PUBLIC_URL
ARG NEXT_PUBLIC_CLIENT_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG AUTH_URL

ENV NEXT_PUBLIC_URL=$NEXT_PUBLIC_URL
ENV NEXT_PUBLIC_CLIENT_URL=$NEXT_PUBLIC_CLIENT_URL
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV AUTH_URL=$AUTH_URL

RUN npm run build

# Stage 2: Production image
FROM node:20 AS production

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/.env ./.env

ENV DATABASE_URL=$DATABASE_URL
ENV DB_USER=$DB_USER
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_NAME=$DB_NAME

ENV AUTH_SECRET=$AUTH_SECRET

ENV SMTP_USER=$SMTP_USER
ENV SMTP_PASSWORD=$SMTP_PASSWORD

ENV GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
ENV GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET

ENV EDGE_STORE_ACCESS_KEY=$EDGE_STORE_ACCESS_KEY
ENV EDGE_STORE_SECRET_KEY=$EDGE_STORE_SECRET_KEY

ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY

ENV STRIPE_WEBHOOK_KEY_SUBSCRIPTION=$STRIPE_WEBHOOK_KEY_SUBSCRIPTION
ENV STRIPE_WEBHOOK_KEY_PRODUCT=$STRIPE_WEBHOOK_KEY_PRODUCT

ENV SRTIPE_STARTER_SUBCRIPTION=$SRTIPE_STARTER_SUBCRIPTION
ENV SRTIPE_PRO_SUBCRIPTION=$SRTIPE_PRO_SUBCRIPTION

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && npm start"]